void call(String image, String namespaceList) 
{
  stage("Show Build Settings")
  {
    println "BUILD SETTINGS"
    println "--------------"
    println "BRANCH_NAME = ${env.BRANCH_NAME}"
    println "CHANGE_ID = ${env.CHANGE_ID}"      
    println "CHANGE_URL = ${env.CHANGE_URL}"      
    println "CHANGE_TITLE = ${env.CHANGE_TITLE}"
    println "CHANGE_AUTHOR = ${env.CHANGE_AUTHOR}"
    println "CHANGE_AUTHOR_DISPLAY_NAME = ${env.CHANGE_AUTHOR_DISPLAY_NAME}"
    println "CHANGE_AUTHOR_EMAIL = ${env.CHANGE_AUTHOR_EMAIL}"
    println "CHANGE_TARGET = ${env.CHANGE_TARGET}"
    println "CHANGE_BRANCH = ${env.CHANGE_BRANCH}"
    println "CHANGE_FORK = ${env.CHANGE_FORK}"
    println "TAG_NAME = ${env.TAG_NAME}"
    println "TAG_TIMESTAMP = ${env.TAG_TIMESTAMP}"
    println "TAG_UNIXTIME = ${env.TAG_UNIXTIME}"
    println "TAG_DATE = ${env.TAG_DATE}"
    println "BUILD_NUMBER = ${env.BUILD_NUMBER}"
    println "BUILD_ID = ${env.BUILD_ID}"
    println "BUILD_DISPLAY_NAME = ${env.BUILD_DISPLAY_NAME}"
    println "JOB_NAME = ${env.JOB_NAME}"
    println "JOB_BASE_NAME = ${env.JOB_BASE_NAME}"
    println "BUILD_TAG = ${env.BUILD_TAG}"
    println "EXECUTOR_NUMBER = ${env.EXECUTOR_NUMBER}"
    println "NODE_NAME = ${env.NODE_NAME}"
    println "NODE_LABELS = ${env.NODE_LABELS}"
    println "WORKSPACE = ${env.WORKSPACE}"
    println "WORKSPACE_TMP = ${env.WORKSPACE_TMP}"
    println "JENKINS_HOME = ${env.JENKINS_HOME}"
    println "JENKINS_URL = ${env.JENKINS_URL}"
    println "BUILD_URL = ${env.BUILD_URL}"
    println "JOB_URL = ${env.JOB_URL}"
    println "GIT_COMMIT = ${env.GIT_COMMIT}"
    println "GIT_PREVIOUS_COMMIT = ${env.GIT_PREVIOUS_COMMIT}"
    println "GIT_PREVIOUS_SUCCESSFUL_COMMIT = ${env.GIT_PREVIOUS_SUCCESSFUL_COMMIT}"
    println "GIT_BRANCH = ${env.GIT_BRANCH}"
    println "GIT_LOCAL_BRANCH = ${env.GIT_LOCAL_BRANCH}"
    println "GIT_CHECKOUT_DIR = ${env.GIT_CHECKOUT_DIR}"
    println "GIT_URL = ${env.GIT_URL}"
    println "GIT_COMMITTER_NAME = ${env.GIT_COMMITTER_NAME}"
    println "GIT_AUTHOR_NAME = ${env.GIT_AUTHOR_NAME}"
    println "GIT_COMMITTER_EMAIL = ${env.GIT_COMMITTER_EMAIL}"
    println "GIT_AUTHOR_EMAIL = ${env.GIT_AUTHOR_EMAIL}"    
    println "--------------"
  }
}
      